// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ExternalLinksController from "./external_links_controller"
application.register("external-links", ExternalLinksController)

import SelectizeController from "./selectize_controller"
application.register("selectize", SelectizeController)
