include:
  - project: "infrastructure-engineering-shared/gitlab-ci-templates"
    file:
      - "lint_docker.yaml"
      - "build_and_scan_docker.yaml"
      - "kubectl_commands.yaml"
      - "sast_scanning.yaml"

variables:
  IMAGE: "tulibraries/manifold"
  HARBOR: "harbor.k8s.temple.edu"
  HELM_EXPERIMENTAL_OCI: "1"
  SAST_EXCLUDED_PATHS: "spec, test, tests, tmp"

.export_variables: &export_variables
  - source .env
  - export VERSION="${DOCKER_IMAGE_VERSION}-${CI_COMMIT_SHORT_SHA}"

before_script:
- *export_variables

stages:
  - lint
  - build
  - tag
  - deploy

lint:
  extends: .lint_docker
  variables:
    DF: ".docker/app/Dockerfile"
  except:
    - tags

build:
  stage: build
  extends: .build_and_scan_image
  variables:
    DF: ".docker/app/Dockerfile --build-arg RAILS_MASTER_KEY=$RAILS_MASTER_KEY --no-cache"
  except:
    - tags

tag:
  stage: tag
  extends: .tag_image
  except:
    - tags

qa_deploy:
  variables:
    IMAGE: $HARBOR/tulibraries/manifold
    RANCHER: rancher-np
    CLUSTER: dev-library0
  stage: deploy
  extends: .helm_setup
  only:
    - qa #Change this once we remove the qa branch
  script:
    - *export_variables
    - helm pull oci://$HARBOR/tulibraries/manifold-charts/manifold --version "0.1.*" --untar
    - helm upgrade manifold oci://$HARBOR/tulibraries/manifold-charts/manifold --version "0.1.*" --history-max=5 --namespace=manifold-qa --values manifold/values.yaml --set image.repository=$IMAGE:$VERSION
