shared:
  "13th Street Entrance of Charles Library":
    building: "Charles Library"
    address: "1210 Polett Walk"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
    space: "13th Street Entrance"
  "Ambler Library":
    building: "Ambler Library"
    address: "580 Meetinghouse Road"
    city: "Ambler"
    state: "PA"
    zip: "19002"
  "Anderson 1221":
    building: "Anderson Hall"
    space: "Room 1221"
    address: "1114 Polett Walk"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
  "Bright Hope Baptist Church, 1601 N. 12th Street":
    building: "Bright Hope Baptist Church"
    address: "1601 N 12th St"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
  "Center for Anti-Racism Research, Mazur Hall, 1114 Polett Walk":
    building: "Mazur Hall"
    address: "1114 Polett Walk"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
  "Charles L. Blockson Afro-American Collection":
    building: "Charles L. Blockson Afro-American Collection"
    address: "1330 Polett Walk"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
    space: "1st Floor"
  "Charles Library Atrium":
    building: "Charles Library"
    address: "1210 Polett Walk"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
    space: "Atrium"
  "Charles Library Event Space":
    building: "Charles Library"
    address: "1210 Polett Walk"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
    space: "Event Space"
  "Charles Library Room 113":
    building: "Charles Library"
    address: "1210 Polett Walk"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
    space: "Room 113"
  "Charles Library Room 201":
    building: "Charles Library"
    address: "1210 Polett Walk"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
    space: "Room 201"
  "Charles Library Room 202":
    building: "Charles Library"
    address: "1210 Polett Walk"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
    space: "Room 202"
  "Charles Library Room 210":
    building: "Charles Library"
    address: "1210 Polett Walk"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
    space: "Room 210"
  "Charles Library Room 401":
    building: "Charles Library"
    address: "1210 Polett Walk"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
    space: "Room 401"
  "Church of the Advocate":
    building: "Church of the Advocate"
    address: "1801 W Diamond St"
    city: "Philadelphia"
    state: "PA"
    zip: "19121"
  "Ginsburg Library":
    building: "Ginsburg Health Sciences Library"
    address: "1900 N. 13th Street"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
  "Ginsburg Library Innovation Space":
    building: "Ginsburg Health Sciences Library"
    address: "1900 N. 13th Street"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
    space: "Innovation Space"
  "Ginsburg Library Room 160":
    building: "Ginsburg Health Sciences Library"
    address: "1900 N. 13th Street"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
    space: "Room 160"
  "Ginsburg Library Room 248":
    building: "Ginsburg Health Sciences Library"
    address: "1900 N. 13th Street"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
    space: "Room 248"
  "Gladfelter 914":
    building: "Gladfelter Hall"
    space: "Room 914"
    address: "1115 Polett Walk"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
  "Howard Gittis Student Center, Room 200C, 1755 N. 13th Street":
    building: "Howard Gittis Student Center"
    space: "Room 200C"
    address: "1755 N 13th St"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
  "Loretta C. Duckworth Scholars Studio":
    building: "Charles Library"
    address: "1210 Polett Walk"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
    space: "Loretta C. Duckworth Scholars Studio"
  "Makerspace Electronics Lab, Scholars Studio in Charles Library Makerspace, Scholars Studio in Charles Library":
    building: "Charles Library"
    address: "1210 Polett Walk"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
    space: "Makerspace Electronics Lab, Scholars Studio"
  "Mazur Hall 821":
    building: "Mazur Hall"
    space: "Room 821"
    address: "1114 Polett Walk"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
  "MERB Lobby":
    building: "MERB"
    space: "Lobby"
    address: "3509 N Broad St"
    city: "Philadelphia"
    state: "PA"
    zip: "19140"
  "Podiatry Library":
    building: "Krausz Library of Podiatric Medicine"
    address: "8th and Race Streets"
    city: "Philadelphia"
    state: "PA"
    zip: "19107"
  "Specialized Computing Lab, Scholars Studio in Charles Library":
    building: "Charles Library"
    address: "1210 Polett Walk"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
    space: "Specialized Computing Lab, Scholars Studio"
  "Student Faculty Center (HSC campus)":
    building: "Student Faculty Center (HSC campus)"
    address: "3340 N Broad St Ste 322"
    city: "Philadelphia"
    state: "PA"
    zip: "19140"
  "Temple Performing Arts Center":
    building: "Temple Performing Arts Center"
    address: "1837 N Broad St"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
  "The Feinstone Lounge, Sullivan Hall":
    building: "Sullivan Hall"
    space: "The Feinstone Lounge"
    address: "1330 Polett Walk"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
  "VR Lab, Scholars Studio in Charles Library":
    building: "Charles Library"
    address: "1210 Polett Walk"
    city: "Philadelphia"
    state: "PA"
    zip: "19122"
    space: "VR Lab, Scholars Studio"
