# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' } { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#
# require Rails.root.join("db/account_seeds.rb") if File.exists?("db/account_seeds.rb")

Subject.create!(name: "Advertising & Marketing")
Subject.create!(name: "Africology & African-American Studies")
Subject.create!(name: "American Studies")
Subject.create!(name: "Anthropology")
Subject.create!(name: "Architecture")
Subject.create!(name: "Art")
Subject.create!(name: "Art Education")
Subject.create!(name: "Art History")
Subject.create!(name: "Asian and Middle Eastern Languages and Studies")
Subject.create!(name: "Bioengineering")
Subject.create!(name: "Biology")
Subject.create!(name: "Biomedical Science")
Subject.create!(name: "Business")
Subject.create!(name: "Chemistry")
Subject.create!(name: "Chinese")
Subject.create!(name: "Civil & Environmental Engineering")
Subject.create!(name: "Communication & Social Influence")
Subject.create!(name: "Communication Management")
Subject.create!(name: "Communication Sciences & Disorders")
Subject.create!(name: "Communication Studies")
Subject.create!(name: "Computer & Information Sciences")
Subject.create!(name: "Criminal Justice")
Subject.create!(name: "Dance")
Subject.create!(name: "Dentistry")
Subject.create!(name: "Earth & Environmental Science")
Subject.create!(name: "Economics")
Subject.create!(name: "Education")
Subject.create!(name: "Electrical & Computer Engineering")
Subject.create!(name: "Engineering, Technology & Management")
Subject.create!(name: "English")
Subject.create!(name: "Environmental Studies")
Subject.create!(name: "Film & Media Arts")
Subject.create!(name: "French")
Subject.create!(name: "Gender, Sexuality & Women's Studies")
Subject.create!(name: "GIS & Mapping")
Subject.create!(name: "Geography & Urban Studies")
Subject.create!(name: "German")
Subject.create!(name: "Global Studies")
Subject.create!(name: "Government Information")
Subject.create!(name: "Greek & Roman Classics")
Subject.create!(name: "Health & Rehabilitation Sciences")
Subject.create!(name: "History")
Subject.create!(name: "Horticulture")
Subject.create!(name: "Italian")
Subject.create!(name: "Jewish Studies")
Subject.create!(name: "Journalism")
Subject.create!(name: "Kinesiology")
Subject.create!(name: "Landscape Architecture")
Subject.create!(name: "Latin American Studies")
Subject.create!(name: "Law")
Subject.create!(name: "LGBT Studies")
Subject.create!(name: "Mathematics")
Subject.create!(name: "Mechanical Engineering")
Subject.create!(name: "Media & Communication")
Subject.create!(name: "Media Studies & Production")
Subject.create!(name: "Medicine")
Subject.create!(name: "Music")
Subject.create!(name: "Music Education")
Subject.create!(name: "Music Therapy")
Subject.create!(name: "Neuroscience")
Subject.create!(name: "Nursing")
Subject.create!(name: "Pharmacy")
Subject.create!(name: "Philosophy")
Subject.create!(name: "Physical Therapy")
Subject.create!(name: "Physician Assistant")
Subject.create!(name: "Physics")
Subject.create!(name: "Planning & Community Development")
Subject.create!(name: "Podiatric Medicine")
Subject.create!(name: "Political Science")
Subject.create!(name: "Portuguese")
Subject.create!(name: "Postbaccalaureate Pre-Health")
Subject.create!(name: "Postbaccalaureate Pre-Med")
Subject.create!(name: "Psychology")
Subject.create!(name: "Public Health")
Subject.create!(name: "Public Policy")
Subject.create!(name: "Public Relations")
Subject.create!(name: "Rehabilitation Sciences")
Subject.create!(name: "Religion")
Subject.create!(name: "Russian")
Subject.create!(name: "Social Work")
Subject.create!(name: "Sociology")
Subject.create!(name: "Spanish")
Subject.create!(name: "Sport & Recreation Management")
Subject.create!(name: "Tourism & Hospitality")
Subject.create!(name: "Theater")
Subject.create!(name: "Urban Bioethics")