# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' } { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#
# require Rails.root.join("db/account_seeds.rb") if File.exists?("db/account_seeds.rb")

SubjectSpecialty.create!(name: "Advertising & Marketing")
SubjectSpecialty.create!(name: "Africology & African-American Studies")
SubjectSpecialty.create!(name: "American Studies")
SubjectSpecialty.create!(name: "Anthropology")
SubjectSpecialty.create!(name: "Architecture")
SubjectSpecialty.create!(name: "Art")
SubjectSpecialty.create!(name: "Art Education")
SubjectSpecialty.create!(name: "Art History")
SubjectSpecialty.create!(name: "Asian and Middle Eastern Languages and Studies")
SubjectSpecialty.create!(name: "Bioengineering")
SubjectSpecialty.create!(name: "Biology")
SubjectSpecialty.create!(name: "Biomedical Science")
SubjectSpecialty.create!(name: "Business")
SubjectSpecialty.create!(name: "Chemistry")
SubjectSpecialty.create!(name: "Chinese")
SubjectSpecialty.create!(name: "Civil & Environmental Engineering")
SubjectSpecialty.create!(name: "Communication & Social Influence")
SubjectSpecialty.create!(name: "Communication Management")
SubjectSpecialty.create!(name: "Communication Sciences & Disorders")
SubjectSpecialty.create!(name: "Communication Studies")
SubjectSpecialty.create!(name: "Computer & Information Sciences")
SubjectSpecialty.create!(name: "Criminal Justice")
SubjectSpecialty.create!(name: "Dance")
SubjectSpecialty.create!(name: "Dentistry")
SubjectSpecialty.create!(name: "Earth & Environmental Science")
SubjectSpecialty.create!(name: "Economics")
SubjectSpecialty.create!(name: "Education")
SubjectSpecialty.create!(name: "Electrical & Computer Engineering")
SubjectSpecialty.create!(name: "Engineering Technology & Management")
SubjectSpecialty.create!(name: "English")
SubjectSpecialty.create!(name: "Environmental Studies")
SubjectSpecialty.create!(name: "Film & Media Arts")
SubjectSpecialty.create!(name: "French")
SubjectSpecialty.create!(name: "Gender Sexuality & Women's Studies")
SubjectSpecialty.create!(name: "GIS & Mapping")
SubjectSpecialty.create!(name: "Geography & Urban Studies")
SubjectSpecialty.create!(name: "German")
SubjectSpecialty.create!(name: "Global Studies")
SubjectSpecialty.create!(name: "Government Information")
SubjectSpecialty.create!(name: "Greek & Roman Classics")
SubjectSpecialty.create!(name: "Health & Rehabilitation Sciences")
SubjectSpecialty.create!(name: "History")
SubjectSpecialty.create!(name: "Horticulture")
SubjectSpecialty.create!(name: "Italian")
SubjectSpecialty.create!(name: "Jewish Studies")
SubjectSpecialty.create!(name: "Journalism")
SubjectSpecialty.create!(name: "Kinesiology")
SubjectSpecialty.create!(name: "Landscape Architecture")
SubjectSpecialty.create!(name: "Latin American Studies")
SubjectSpecialty.create!(name: "Law")
SubjectSpecialty.create!(name: "LGBT Studies")
SubjectSpecialty.create!(name: "Mathematics")
SubjectSpecialty.create!(name: "Mechanical Engineering")
SubjectSpecialty.create!(name: "Media & Communication")
SubjectSpecialty.create!(name: "Media Studies & Production")
SubjectSpecialty.create!(name: "Medicine")
SubjectSpecialty.create!(name: "Music")
SubjectSpecialty.create!(name: "Music Education")
SubjectSpecialty.create!(name: "Music Therapy")
SubjectSpecialty.create!(name: "Neuroscience")
SubjectSpecialty.create!(name: "Nursing")
SubjectSpecialty.create!(name: "Pharmacy")
SubjectSpecialty.create!(name: "Philosophy")
SubjectSpecialty.create!(name: "Physical Therapy")
SubjectSpecialty.create!(name: "Physician Assistant")
SubjectSpecialty.create!(name: "Physics")
SubjectSpecialty.create!(name: "Planning & Community Development")
SubjectSpecialty.create!(name: "Podiatric Medicine")
SubjectSpecialty.create!(name: "Political Science")
SubjectSpecialty.create!(name: "Portuguese")
SubjectSpecialty.create!(name: "Postbaccalaureate Pre-Health")
SubjectSpecialty.create!(name: "Postbaccalaureate Pre-Med")
SubjectSpecialty.create!(name: "Psychology")
SubjectSpecialty.create!(name: "Public Health")
SubjectSpecialty.create!(name: "Public Policy")
SubjectSpecialty.create!(name: "Public Relations")
SubjectSpecialty.create!(name: "Rehabilitation Sciences")
SubjectSpecialty.create!(name: "Religion")
SubjectSpecialty.create!(name: "Russian")
SubjectSpecialty.create!(name: "Social Work")
SubjectSpecialty.create!(name: "Sociology")
SubjectSpecialty.create!(name: "Spanish")
SubjectSpecialty.create!(name: "Sport & Recreation Management")
SubjectSpecialty.create!(name: "Tourism & Hospitality")
SubjectSpecialty.create!(name: "Theater")
SubjectSpecialty.create!(name: "Urban Bioethics")